field_mapping = {
    "device_frmpayload_data_barometer_2": None,
    "device_frmpayload_data_battery": None,
    "device_frmpayload_data_byte1": None,
    "device_frmpayload_data_byte10": None,
    "device_frmpayload_data_byte2": None,
    "device_frmpayload_data_byte3": None,
    "device_frmpayload_data_byte4": None,
    "device_frmpayload_data_byte5": None,
    "device_frmpayload_data_byte6": None,
    "device_frmpayload_data_byte7": None,
    "device_frmpayload_data_byte8": None,
    "device_frmpayload_data_byte9": None,
    "device_frmpayload_data_configCarried": None,
    "device_frmpayload_data_configInconsistency": None,
    "device_frmpayload_data_frame": None,
    "device_frmpayload_data_frameCounter": "object_frameCounter",
    "device_frmpayload_data_hardwareError": "object_harwareError",
    "device_frmpayload_data_humidity_sensor_2": None,
    "device_frmpayload_data_humidity_sensor_3": None,
    "device_frmpayload_data_illuminance_sensor_4": None,
    "device_frmpayload_data_lowBattery": "object_lowBattery",
    "device_frmpayload_data_status": None,
    "device_frmpayload_data_temperature1": "object_temperature1",
    "device_frmpayload_data_temperature2": "object_temperature2",
    "device_frmpayload_data_temperatureExtern": "object_temperature1",
    "device_frmpayload_data_temperatureIntern": "object_temperature2",
    "device_frmpayload_data_temperature_sensor_1": None,
    "device_uplink": None,
}

target_measurements = [
    "T_S_25",
    "T_S_26",
    "T_S_28",
    "T_S_29",
    "T_S_30",
    "T_S_31",
    "T_S_32",
    "T_S_33",
    "T_S_34",
    "T_S_35",
    "T_S_36",
    "T_S_37",
    "T_S_38",
    "T_S_39",
    "T_S_40",
    "T_S_41",
    "T_S_42",
    "T_S_43",
    "T_S_44",
    "T_S_45",
    "T_S_46",
    "T_S_47",
    "T_S_48",
    "T_S_49",
    "T_S_50",
]

measurements_with_extern_temperature = [
    "T_HA_02",
    "T_S_01",
    "T_S_02",
    "T_S_03",
    "T_S_04",
    "T_S_05",
    "T_S_06",
    "T_S_07",
    "T_S_08",
    "T_S_09",
    "T_S_10",
    "T_S_11",
    "T_S_25",
]
